AGNO_OS_ID: str = "AGNO_OS_ID"
AGNO_OS_NAME: str = "AGNO_OS_NAME"
AGNO_OS_ROOT: str = "AGNO_OS_ROOT"
AGNO_OS_INFRA_DIR: str = "AGNO_OS_INFRA_DIR"
REQUIREMENTS_FILE_PATH_ENV_VAR: str = "REQUIREMENTS_FILE_PATH"

AWS_REGION_ENV_VAR: str = "AWS_REGION"
AWS_DEFAULT_REGION_ENV_VAR: str = "AWS_DEFAULT_REGION"
AWS_PROFILE_ENV_VAR: str = "AWS_PROFILE"
